#version 430

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

layout(binding = 0, rgba8) uniform image3D voxelColor;

void main() {
    ivec3 threadId = ivec3(gl_GlobalInvocationID.xyz);

    if (any(greaterThan(threadId, imageSize(voxelColor).xyz))) {
        return;
    }

    vec4 value = imageLoad(voxelColor, threadId);
    if (value.a > 0) {
        value.a = 1;
        imageStore(voxelColor, threadId, value);
    }
}