#version 430

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(binding = 0, rgba8) uniform image3D src;

uniform float temporalDecay;

void main() {
    ivec3 threadId = ivec3(gl_GlobalInvocationID.xyz);
    ivec3 srcSize = imageSize(src);

    if (any(greaterThan(threadId, srcSize)))
        return;

    vec4 value = imageLoad(src, threadId);
    value *= temporalDecay;
    imageStore(src, threadId, value);
}
